# -*- coding: utf-8 -*-
"""Atividade final - limpeza dos dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icWYbfT7986gfe5oXfcbrGPfZgGtK6QH
"""

from google.colab import files
import pandas as pd
import io
import zipfile

# Upload the files
uploaded = files.upload()

# Assuming you uploaded a zip file containing the CSV files
with zipfile.ZipFile(io.BytesIO(uploaded[list(uploaded.keys())[0]]), 'r') as zip_ref:
  # Extract all files to the current directory
  zip_ref.extractall('.')

# Read the files into pandas DataFrames, specifying the encoding if needed
# Make sure file names match the ones inside the .zip file.
# Use the actual filenames if they are different.
orders = pd.read_csv('olist_orders_dataset.csv')
order_items = pd.read_csv('olist_order_items_dataset.csv')
products = pd.read_csv('olist_products_dataset.csv')
customers = pd.read_csv('olist_customers_dataset.csv')

# Calcule dias para entrega
orders['delivery_time'] = (pd.to_datetime(orders['order_delivered_customer_date']) -
                         pd.to_datetime(orders['order_purchase_timestamp'])).dt.days

# Junte com dados de clientes
df_merged = orders.merge(customers, on='customer_id')

# Média por estado
delivery_by_state = df_merged.groupby('customer_state')['delivery_time'].mean().sort_values()

# Gráfico
delivery_by_state.plot(kind='bar', figsize=(10, 4))
plt.title("Tempo Médio de Entrega (dias) por Estado")
plt.ylabel("Dias")

sns.scatterplot(data=order_items, x='price', y='freight_value', alpha=0.5)
plt.title("Relação Preço vs. Frete")

# Junte itens de pedido com produtos
df_products = order_items.merge(products, on='product_id')

# Conte vendas por categoria
top_categories = df_products['product_category_name'].value_counts().head(10)

# Gráfico
top_categories.plot(kind='barh', color='skyblue')
plt.title("Top 10 Categorias Mais Vendidas")

reviews = pd.read_csv('olist_order_reviews_dataset.csv')
sns.countplot(data=reviews, x='review_score')
plt.title("Distribuição das Avaliações (1-5)")

orders['order_purchase_year_month'] = pd.to_datetime(orders['order_purchase_timestamp']).dt.to_period('M')
canceled_orders = orders[orders['order_status'] == 'canceled']

canceled_orders.groupby('order_purchase_year_month').size().plot()
plt.title("Cancelamentos por Mês")

# Preencha tempos de entrega faltantes com a mediana
orders['delivery_time'].fillna(orders['delivery_time'].median(), inplace=True)

# Converta categorias para minúsculas
products['product_category_name'] = products['product_category_name'].str.lower()

# 1. Valor total do pedido (preço + frete)
order_items['total_price'] = order_items['price'] + order_items['freight_value']

# 2. Mês/ano da compra
orders['purchase_month'] = pd.to_datetime(orders['order_purchase_timestamp']).dt.to_period('M')

orders.to_csv('orders_clean.csv', index=False)
order_items.to_csv('order_items_clean.csv', index=False)

order_items.to_csv('order_items_clean.csv', index=False, encoding='utf-8')

order_items.to_csv('order_items_clean_fixed.csv', index=False, encoding='utf-8', sep=',')

# Salvar DataFrames como CSV
orders.to_csv('orders_clean.csv', index=False)
order_items.to_csv('order_items_clean.csv', index=False)
customers.to_csv('customers_clean.csv', index=False)
products.to_csv('products_clean.csv', index=False)

from google.colab import files
files.download('orders_clean.csv')
files.download('order_items_clean.csv')

# Versão otimizada para exportação
import os # Import the os module

def prepare_for_export(df):
    # Converter todas as colunas de texto para string
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].astype(str)

    # Converter períodos para string
    if 'purchase_month' in df.columns:
        df['purchase_month'] = df['purchase_month'].astype(str)

    return df

# Preparar e exportar os dados
order_items_clean = prepare_for_export(order_items)
order_items_clean.to_csv('order_items_clean_final.csv',
                        index=False,
                        encoding='utf-8',
                        date_format='%Y-%m-%d')

# Verificação final
print("Verificação final do arquivo:")
print(f"Número de linhas: {len(order_items_clean)}")
print(f"Tamanho do arquivo: {os.path.getsize('order_items_clean_final.csv')/1024/1024:.2f} MB") # Now os is defined and can be used
print("\nPrimeiras linhas:")
print(order_items_clean.head(3))

# Download
from google.colab import files
files.download('order_items_clean_final.csv')